## 1. Integers and Floating Point Numbers

| Types Supported |
| --------------- |
| `Int8` |
| `UInt8` |
| `Int16` |
| `UInt16` |
| `Int32` |
| `UInt32` |
| `Int64` |
| `UInt64` |
| `Int128` |
| `UInt128` |
| `Bool` |
| `Float16` |
| `Float32` |
| `Float64` |

In [1]:
using BenchmarkTools

In [2]:
Sys.WORD_SIZE  # I have a Win64 system so the output will be => 64

64

In [3]:
display(0xdeadbeef)        # Hexadecimal numbers
display(0b01010)           # Binary number
display(bitstring(123))    # Returns the bit string of a integer number
display(bitstring(0.0))    # Returns the bitstring of a floating point number

0xdeadbeef

0x0a

"0000000000000000000000000000000000000000000000000000000001111011"

"0000000000000000000000000000000000000000000000000000000000000000"

In [4]:
1 % 0 # Throws a divide error

DivideError: DivideError: integer division error

In [5]:
rem(1, 0) # Throws a divide error

DivideError: DivideError: integer division error

In [6]:
display(eps(Float16)) # Displays the constant to get the
display(eps(Float32)) # next floating point number in the
display(eps(Float64)) # of the required bits

Float16(0.000977)

1.1920929f-7

2.220446049250313e-16

## 2. Mathematical Operations and Elementary functions

| Rounding Functions |
| ------------------ |
| `round(x)` |
| `round(dtype, x)` |
| `floor(x)` |
| `floor(dtype, x)` |
| `ciel(x)` |
| `ciel(dtype, x)` |
| `trunc(x)` |
| `trunc(dtype, x)` |

| Division Functions |
| ------------------ |
|  |

In [7]:
0.0 == -0.0 # Value comparision

true

In [8]:
NaN == NaN # NaN is not equal to NaN

false

In [9]:
[1 NaN] == [1 NaN] # So, this also returns false

false

In [10]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 > 0 # Expressions can be chained

true

In [11]:
0 .< [0 1 2 3 4 5 4 3 2 1] .< 2 # Element-wise value comparision

1×10 BitArray{2}:
 0  1  0  0  0  0  0  0  0  1

In [12]:
# Julia provides additional functions to test numbers for special values,
# which can be useful in situations like hash key comparisons
display(isequal(0.0, -0.0))                       # Hash Key comparision
display(isfinite(10000000000000000000000000.0))   # Is it finite?
display(isinf(Inf32))                             # Is it infinite?
display(isinf(NaN))                               # Is it infinite?
display(isnan(NaN64))

false

true

true

false

true

In [13]:
f(x) = x^2
x = randn(5, 5)
display(f.(x))
display(f(x))

5×5 Array{Float64,2}:
 0.0552384  0.90968   0.0181371   0.885221    0.0224983
 2.66467    0.105989  0.00303145  2.3591      0.000679161
 1.02051    4.95485   0.0694276   0.00225464  0.702997
 0.199118   1.13412   0.0762447   1.80769     0.00180788
 1.01977    0.310666  0.083383    0.610742    0.388838

5×5 Array{Float64,2}:
 -0.794325  -0.704937   -0.246761    2.38518   0.0102218
 -0.619533   0.0476841   0.619042   -1.00628   0.20097
  2.79447   -0.0690706   0.338141   -1.88956  -0.652259
 -1.47933   -2.79507    -0.337554    3.84311   0.409882
  0.661776  -0.244643    0.0649537  -1.43031   0.734665

In [14]:
using Base

In [15]:
println(Base.operator_precedence(:+), " ", Base.operator_precedence(:*), " ", Base.operator_precedence(:.))
println(Base.operator_precedence(:sin), " ", Base.operator_precedence(:+=), " ", Base.operator_precedence(:(=)))

11 12 17
0 1 1


In [16]:
-4 % 5 # true division unlike python which is good :-)

-4

## 3. Convertions

Julia supports three forms of numerical conversion, which differ in their handling of inexact conversions.

The notation T(x) or convert(T,x) converts x to a value of type T.

 - If T is a floating-point type, the result is the nearest representable value, which could be positive or negative infinity.
 - If T is an integer type, an InexactError is raised if x is not representable by T.
 - x % T converts an integer x to a value of integer type T congruent to x modulo 2^n, where n is the number of bits in T. In other words, the binary representation is truncated to fit.

The Rounding functions take a type T as an optional argument. For example, round(Int,x) is a shorthand for Int(round(x)).

In [17]:
import Base:convert

In [18]:
@show 127 % Int8
@show 128 % Int8
@show round(Int8,127.4)
round(Int8,127.6)

127 % Int8 = 127
128 % Int8 = -128
round(Int8, 127.4) = 127


InexactError: InexactError: trunc(Int8, 128.0)

In [19]:
@which convert(Complex{Int32}, 1+2im)

convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7

In [20]:
# You can overload convert method with user defined datatypes
convert(::Type{Int8}, x::String) = [Number(i) for i in x]

convert (generic function with 184 methods)

In [21]:
convert(Int8, "tirth")

5-element Array{UInt32,1}:
 0x00000074
 0x00000069
 0x00000072
 0x00000074
 0x00000068

## 4. Signed and absolute valued functions

| Function | Description |
| -------- | ----------- |
| `abs(x)` | Abs. |
| `abs2(x)` | Absolute value squared! Can be useful for finding euclidean distance. |
| `sign(x)` | Sign. |
| `signbit(x)` | Indicating weather the signbit is on or off. |
| `copysign(x, y)` | A value with magnitude of x and sign of y. |
| `flipsign(x, y)` | A value with magnitude of x and sign of x\*y |

In [22]:
@show abs(-3 + 4im);
@show abs2(-3 + 4im);
@show sign(-3);
@show sign(3);
@show sign(0);
@show signbit(3);
@show signbit(-3);
@show copysign(3, -4);
@show flipsign(-3, -4);

abs(-3 + 4im) = 5.0
abs2(-3 + 4im) = 25
sign(-3) = -1
sign(3) = 1
sign(0) = 0
signbit(3) = false
signbit(-3) = true
copysign(3, -4) = -3
flipsign(-3, -4) = 3


## 5. Complex and Rational Numbers

In [23]:
# New to complex numbers only.
@show angle(2 + 2im) / pi * 180
@show sqrt(-1 + 0im)
@show isequal(1, 1 + 0im)
# Rational Numbers and thier unique operations
@show 4 // 8
@show 6 // 200
@show 5 // 8 * 3 // 12
@show 3 // 4 + 2 // 8
@show float(3 // 2)
@show isequal(3 // 2, 3/2);
# Floating point numbers have highest precedence.
# So, rantional numbers get typecasted to float
# when operated with a float. But rational numbers have
# a higher precedence than int so they remain rational
# when operated with an int.
@show 3 // 4 * (10)
@show 3 // 4 * (10.);

(angle(2 + 2im) / pi) * 180 = 45.0
sqrt(-1 + 0im) = 0.0 + 1.0im
isequal(1, 1 + 0im) = true
4 // 8 = 1//2
6 // 200 = 3//100
5 // 8 * 3 // 12 = 5//32
3 // 4 + 2 // 8 = 1//1
float(3 // 2) = 1.5
isequal(3 // 2, 3 / 2) = true
3 // 4 * 10 = 15//2
3 // 4 * 10.0 = 7.5


## 6. Strings!!

Some things to note:
 - Strings in Julia support all unicode characters with UTF-8 encoding.
 - All string types are subtypes of `AbstractString`. If you create a function expecting a string argument, you should declare the type as `AbstractString` in order to accept any string type.
 - Strings are immutable in Julia! Once assigned, they cannot be changed.
 - Char is implemented as an `AbstractChar` and is a 32 bit primitive type.

In [24]:
isvalid(Char, 0x1f0000)

false

In [25]:
# Interesting use of `end`
name = "Tirth Patel"
@show name[1]
@show name[end]
@show name[end-1]
# Slicing in Julia!
@show name[7:9]   # 8 inclusive!!!!
@show name[7:end]
# Notice that name[k] and nake[k:k] don't give the same results!
@show name[6:6] # string output
@show name[6] # char output
# SubString is another type of string which sub classes `AbstractString`
# and can be created using `SubString`.
@show SubString(name, 7, 9);

name[1] = 'T'
name[end] = 'l'
name[end - 1] = 'e'
name[7:9] = "Pat"
name[7:end] = "Patel"
name[6:6] = " "
name[6] = ' '
SubString(name, 7, 9) = "Pat"


In [26]:
typeof(name[6:9])

String

In [27]:
typeof(SubString(name, 6, 9))

SubString{String}

#### Note : `SubString` creates a VIEW while slicing creates a COPY!

In [28]:
# This shows that `SubString` creates a view while slicing creates a copy!!
str = "wow this is awesome" ^ 100
@btime str[6:900]
@btime SubString(str, 6, 900);

  91.121 ns (1 allocation: 1008 bytes)
  77.996 ns (1 allocation: 32 bytes)


### 6.1. Unicode and UTF-8

Whether these Unicode characters are displayed as escapes or shown as special characters depends on your terminal's locale settings and its support for Unicode. String literals are encoded using the UTF-8 encoding. UTF-8 is a variable-width encoding, meaning that not all characters are encoded in the same number of bytes ("code units"). In UTF-8, ASCII characters — i.e. those with code points less than 0x80 (128) – are encoded as they are in ASCII, using a single byte, while code points 0x80 and above are encoded using multiple bytes — up to four per character

String indices in Julia refer to code units (= bytes for UTF-8), the fixed-width building blocks that are used to encode arbitrary characters (code points). This means that not every index into a `String` is necessarily a valid index for a character. If you index into a string at such an invalid byte index, an error is thrown

In [29]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [30]:
# Error because In this case, the character ∀ is a three-byte character,
# so the indices 2 and 3 are invalid and the next character's index is 4.
s[2]

StringIndexError: StringIndexError("∀ x ∃ y", 2)

In [31]:
# this next valid index can be computed by nextind(s,1), and the next index after that by nextind(s,4) and so on.
@show nextind(s, 1);

nextind(s, 1) = 4


In [32]:
# Since end is always the last valid index into a collection,
# end-1 references an invalid byte index if the second-to-last
# character is multibyte
s[end-2]

StringIndexError: StringIndexError("∀ x ∃ y", 9)

In [33]:
# similarly you can use `prevind`
@show s[prevind(s, end, 1)];

s[prevind(s, end, 1)] = ' '


In [34]:
# We can also use `firstindex` and `lastindex` in a `for` loop
@show [i for i in s]
# We can also use `firstindex` and `lastindex` in a big `for` loop!!
for i in firstindex(s):lastindex(s)
    try
        print(s[i], " ");
    catch
        # ignore index error
    end
end

[i for i = s] = ['∀', ' ', 'x', ' ', '∃', ' ', 'y']
∀   x   ∃   y 

In [35]:
?eachindex # Returns a `iterable` or `collections` object

search: eachindex



```
eachindex(A...)
```

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a [`UnitRange`](@ref) if all inputs have fast linear indexing, a [`CartesianIndices`](@ref) otherwise). If the arrays have different sizes and/or dimensionalities, a DimensionMismatch exception will be thrown.

# Examples

```jldoctest
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
```


In [36]:
collect(eachindex(s))

7-element Array{Int64,1}:
  1
  4
  5
  6
  7
 10
 11

In [37]:
"Hello World" == "Hello World", "1 + 2 = 3" == "1 + 2 = $(1+2)"

(true, true)

### 6.2. String Methods!

In [38]:
# findfirst => Find firt occurence of something
findfirst(isequal('t'), "Tirth Patel")
# isequal(x) -> Create a function that compares its argument
#               to x using isequal, i.e. a function equivalent
#               to y -> isequal(y, x). The returned function
#               is of type Base.Fix2{typeof(isequal)}, which
#               can be used to implement specialized methods.

4

In [39]:
# finidlast
findlast(isequal('t'), "Tirth Patel")

9

In [40]:
# If not present, returns `nothing` object
typeof(findfirst(isequal('x'), "Tirth Patel"))

Nothing

In [41]:
# findnext and findprev helps to find the next occurence
# of a character and the previous occurence of a char.
@show findnext(isequal('t'), "Tirth Patel", 6)
@show findprev(isequal('t'), "Tirth Patel", 6);

findnext(isequal('t'), "Tirth Patel", 6) = 9
findprev(isequal('t'), "Tirth Patel", 6) = 4


In [42]:
# `occursin` function checks if a substing
# occurs in a string
@show occursin("Tirth", "Tirth Patel")
@show occursin('t', "Tirth Patel");

occursin("Tirth", "Tirth Patel") = true
occursin('t', "Tirth Patel") = true


In [43]:
# You can also use the `in` operator
# to check the occurence of an element
#  in a container.
@show 't' in "Tirth Patel"
@show "Tirth" in ["Tirth", "Patel"];

't' in "Tirth Patel" = true
"Tirth" in ["Tirth", "Patel"] = true


In [44]:
# Some other very obvious string methods
@show length("Tirth Patel")
@show length("\u2200 x \u2203 y")
@show length("\u2200 x \u2203 y", 3, 9) # the number of valid character indices in str from 3 to 9
@show thisind("\u2200 x \u2203 y", 3) # valid index to which 3 points which is 1.
@show nextind("\u2200 x \u2203 y", 2, 4)
@show prevind("\u2200 x \u2203 y", 9, 4);

length("Tirth Patel") = 11
length("∀ x ∃ y") = 7
length("∀ x ∃ y", 3, 9) = 4
thisind("∀ x ∃ y", 3) = 1
nextind("∀ x ∃ y", 2, 4) = 7
prevind("∀ x ∃ y", 9, 4) = 4


### 6.3. Regular Expressions in Julia

In [45]:
# TODO

## 7. Functions

In [46]:
# Normal Function
function f(x)
    return x .^ 2
end

# Inline function
f(x, y) = x .* y

# Lambda Function
lambda = x -> x .^ 2

#5 (generic function with 1 method)

In [47]:
f, lambda

(f, var"#5#6"())

In [48]:
x = randn(100, 1);

In [49]:
@btime f(x);

  76.471 ns (1 allocation: 896 bytes)


In [50]:
@btime f(x);

  80.394 ns (1 allocation: 896 bytes)


In [51]:
@btime lambda(x);

  78.306 ns (1 allocation: 896 bytes)


In [52]:
# if no `return` keyword is found, julia returns the
# last evaluated expression
function f(x,y,z)
    x .+ y .+ z
end

f([1 2], [3 4], [5 6])

1×2 Array{Int64,2}:
 9  12

In [53]:
# We can `return nothing` if we dont want the function
# to return anything.
function noreturn(x)
    println("x = $(x)");
    return nothing
end

typeof(noreturn([1. 2.]))

x = [1.0 2.0]


Nothing

In [54]:
# We can type the arguments to get very very highly
# efficient assembly code and super fast execution.
function typedf(x::Array{Float64}, y::Array{Float64}, z::Array{Float64})::Array{Float64}
    if all(y .< x) && all(z .< x)
        return x
    end
    if all(x .< y) && all(z .< y)
        return y
    end
    return z
end

typedf (generic function with 1 method)

In [55]:
@btime typedf(x, x, x);

  422.106 ns (4 allocations: 288 bytes)


In [56]:
# Tuples
@show (1, 2, 3)
@show (1, "Tirth Patel", 3//4);

(1, 2, 3) = (1, 2, 3)
(1, "Tirth Patel", 3 // 4) = (1, "Tirth Patel", 3//4)


In [57]:
# Named Tuples
nt = (name="Tirth", rollno="18BCE243", rank=1)

@show nt

println("Name : $(nt.name)")
println("Roll No : $(nt.rollno)")
println("Rank : $(nt.rank)")

nt = (name = "Tirth", rollno = "18BCE243", rank = 1)
Name : Tirth
Roll No : 18BCE243
Rank : 1


In [58]:
# Functions with multuiple return values
function multireturn(x, y)
    return x .+ y, x .* y
end

multireturn([1., 2.], [3., 4.])

([4.0, 6.0], [3.0, 8.0])

In [59]:
x, y = multireturn([1. 2.], 3.)
println(x)
println(y)

[4.0 5.0]
[3.0 6.0]


In [60]:
# Argument destucting : Using this we can name
# the arguments in a tuple when passed to a function
function adf((a,b),c)
    return a .* b .+ c
end

adf(([1. 2.], [3. 4.]), [5. 6.])

1×2 Array{Float64,2}:
 8.0  14.0

In [61]:
# Varargs
function varargf(a, b, c...)
    # + operator is also a function and
    # so is every operation. so we can pass
    # varargs directly to + function
    return +(a, b, c...)
end

varargf([1. 2.], [3. 4.], [5. 6.], [7. 8.], [9. 10.])

1×2 Array{Float64,2}:
 25.0  30.0

In [62]:
a = [1, 2, 3, 4]

+(a...) # Arrays can also be "unpacked" like python.

10

In [63]:
?...

search:



```
...
```

The "splat" operator, `...`, represents a sequence of arguments. `...` can be used in function definitions, to indicate that the function accepts an arbitrary number of arguments. `...` can also be used to apply a function to a sequence of arguments.

# Examples

```jldoctest
julia> add(xs...) = reduce(+, xs)
add (generic function with 1 method)

julia> add(1, 2, 3, 4, 5)
15

julia> add([1, 2, 3]...)
6

julia> add(7, 1:100..., 1000:1100...)
111107
```


In [64]:
# Optional Arguments

function adder(a, b=1., c=1.)
    return a .+ b .+ c
end

@show adder(10, 2, 3)
@show adder(10, 2)
@show adder(10);

adder(10, 2, 3) = 15
adder(10, 2) = 13.0
adder(10) = 12.0


In [65]:
# Keyword only arguments : Insert a `;` to make keyword only args
function keywordf(x1::Array{Float64,2}, x2::Array{Float64,2}; ls::Float64=1., amp::Float64=1.)::Array{Float64,2}
    res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1)
    res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1, size(x2)[1])
    res = res .- 2 .* (x1*x2')
    res = res ./ (2 .* ls.^2)
    return (amp.^2).*exp.(-res)
end

keywordf (generic function with 1 method)

In [66]:
x1 = randn(2000, 20)
x2 = randn(2000, 20);

In [67]:
@btime keywordf(x1, x2);

  123.660 ms (41054 allocations: 184.68 MiB)


In [68]:
# Do-Block syntax for function arguments
# We can vectorize the computation over multiple
# vectors using map and a `begin` `end` syntax.
map(args -> begin
                x1, x2, ls, amp = args
                res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1)
                res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1, size(x2)[1])
                res = res .- 2 .* (x1*x2')
                res = res ./ (2 .* ls.^2)
                return (amp.^2).*exp.(-res)
            end,
    [(x1, x2, 1., 1.), (x1, x2, 2., 3.)]
);

In [69]:
# Another way to write the same code is using `do` block:
map([(x1, x2, 1., 1.), (x1, x2, 2., 3.)]) do args
    x1, x2, ls, amp = args
    res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1)
    res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1, size(x2)[1])
    res = res .- 2 .* (x1*x2')
    res = res ./ (2 .* ls.^2)
    return (amp.^2).*exp.(-res)
end;

### How does the `do` `end` block work??

Let's take the example below

```julia
func(...) do args
    # do something
end
```

It creates a lambda function with arguments `args` and the code between `do` `end` as function body. Then, it passes this lambda function to the function `func` as the first argument and the `...` as remaining arguments. After processing the `...` args, the function `func` calls the lambda function passing it these processed arguments. To make it clearer, let's take the example below

```julia
function func(f::Function, args...)
    # some preprocessing to get the arguments
    # for the lambda function
    fargs = preprocessor(args...)
    try
        res = f(fargs...)
    finally
        # do some post processing
        postprocessor(res...)
    end
end
```

In [73]:
# do blocks are like context manages in Python!!!
# An Example of opening and writing to a file is shown
open("context_managers_in_julia.md", "w") do f
    write(f, "## Do block in Julia\n\n")
    write(f, "This file was made using Julia's context managers!\n")
    write(f, "Isn't it awesome!\n")
end;

In [75]:
# Function composition

# Julia uses a lot of mathematical
# expressions which is good!
(sqrt ∘ +)(3.0, 6.0) # function composition => (f ∘ g)(x)  ≣  f(g(x))

3.0

In [79]:
# Composition of Function

# Julia is awesome, right?
@show 3.0 + 6.0 |> sqrt
@show ["This", "is", "a", "string"] .|> [uppercase, reverse, titlecase, length];

3.0 + 6.0 |> sqrt = 3.0
["This", "is", "a", "string"] .|> [uppercase, reverse, titlecase, length] = Any["THIS", "si", "A", 6]
