## 1. Integers and Floating Point Numbers

| Types Supported |
| --------------- |
| `Int8` |
| `UInt8` |
| `Int16` |
| `UInt16` |
| `Int32` |
| `UInt32` |
| `Int64` |
| `UInt64` |
| `Int128` |
| `UInt128` |
| `Bool` |
| `Float16` |
| `Float32` |
| `Float64` |

In [1]:
using BenchmarkTools

In [2]:
Sys.WORD_SIZE  # I have a Win64 system so the output will be => 64

64

In [3]:
display(0xdeadbeef)        # Hexadecimal numbers
display(0b01010)           # Binary number
display(bitstring(123))    # Returns the bit string of a integer number
display(bitstring(0.0))    # Returns the bitstring of a floating point number

0xdeadbeef

0x0a

"0000000000000000000000000000000000000000000000000000000001111011"

"0000000000000000000000000000000000000000000000000000000000000000"

In [4]:
1 % 0 # Throws a divide error

DivideError: DivideError: integer division error

In [5]:
rem(1, 0) # Throws a divide error

DivideError: DivideError: integer division error

In [6]:
display(eps(Float16)) # Displays the constant to get the
display(eps(Float32)) # next floating point number in the
display(eps(Float64)) # of the required bits

Float16(0.000977)

1.1920929f-7

2.220446049250313e-16

## 2. Mathematical Operations and Elementary functions

| Rounding Functions |
| ------------------ |
| `round(x)` |
| `round(dtype, x)` |
| `floor(x)` |
| `floor(dtype, x)` |
| `ciel(x)` |
| `ciel(dtype, x)` |
| `trunc(x)` |
| `trunc(dtype, x)` |

| Division Functions |
| ------------------ |
|  |

In [7]:
0.0 == -0.0 # Value comparision

true

In [8]:
NaN == NaN # NaN is not equal to NaN

false

In [9]:
[1 NaN] == [1 NaN] # So, this also returns false

false

In [10]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 > 0 # Expressions can be chained

true

In [11]:
0 .< [0 1 2 3 4 5 4 3 2 1] .< 2 # Element-wise value comparision

1×10 BitArray{2}:
 0  1  0  0  0  0  0  0  0  1

In [12]:
# Julia provides additional functions to test numbers for special values,
# which can be useful in situations like hash key comparisons
display(isequal(0.0, -0.0))                       # Hash Key comparision
display(isfinite(10000000000000000000000000.0))   # Is it finite?
display(isinf(Inf32))                             # Is it infinite?
display(isinf(NaN))                               # Is it infinite?
display(isnan(NaN64))

false

true

true

false

true

In [13]:
f(x) = x^2
x = randn(5, 5)
display(f.(x))
display(f(x))

5×5 Array{Float64,2}:
 1.01006    0.00544818  0.0581357  0.0569637  1.53661
 0.0145293  2.6873e-5   0.101005   0.60903    0.00898021
 0.344998   0.127699    0.634226   1.53318    0.287047
 0.173543   0.940149    3.08884    0.184143   0.5347
 3.60102    0.40974     0.189512   0.98477    0.000587706

5×5 Array{Float64,2}:
 -1.29116    0.573659  -0.531053  -1.12663    -1.17742
  0.569836   0.818525  -1.556      0.185487   -0.593317
 -0.514136  -1.78662    3.29883   -0.0617699   2.01334
 -0.232276   0.654312  -1.3724     2.29194    -1.03462
  2.09601    0.678768  -1.66205   -1.94138    -2.90479

In [14]:
using Base

In [15]:
println(Base.operator_precedence(:+), " ", Base.operator_precedence(:*), " ", Base.operator_precedence(:.))
println(Base.operator_precedence(:sin), " ", Base.operator_precedence(:+=), " ", Base.operator_precedence(:(=)))

11 12 17
0 1 1


In [16]:
-4 % 5 # true division unlike python which is good :-)

-4

## 3. Convertions

Julia supports three forms of numerical conversion, which differ in their handling of inexact conversions.

The notation T(x) or convert(T,x) converts x to a value of type T.

 - If T is a floating-point type, the result is the nearest representable value, which could be positive or negative infinity.
 - If T is an integer type, an InexactError is raised if x is not representable by T.
 - x % T converts an integer x to a value of integer type T congruent to x modulo 2^n, where n is the number of bits in T. In other words, the binary representation is truncated to fit.

The Rounding functions take a type T as an optional argument. For example, round(Int,x) is a shorthand for Int(round(x)).

In [17]:
import Base:convert

In [18]:
@show 127 % Int8
@show 128 % Int8
@show round(Int8,127.4)
round(Int8,127.6)

127 % Int8 = 127
128 % Int8 = -128
round(Int8, 127.4) = 127


InexactError: InexactError: trunc(Int8, 128.0)

In [19]:
@which convert(Complex{Int32}, 1+2im)

convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7

In [20]:
# You can overload convert method with user defined datatypes
convert(::Type{Int8}, x::String) = [Number(i) for i in x]

convert (generic function with 184 methods)

In [21]:
convert(Int8, "tirth")

5-element Array{UInt32,1}:
 0x00000074
 0x00000069
 0x00000072
 0x00000074
 0x00000068

## 4. Signed and absolute valued functions

| Function | Description |
| -------- | ----------- |
| `abs(x)` | Abs. |
| `abs2(x)` | Absolute value squared! Can be useful for finding euclidean distance. |
| `sign(x)` | Sign. |
| `signbit(x)` | Indicating weather the signbit is on or off. |
| `copysign(x, y)` | A value with magnitude of x and sign of y. |
| `flipsign(x, y)` | A value with magnitude of x and sign of x\*y |

In [22]:
@show abs(-3 + 4im);
@show abs2(-3 + 4im);
@show sign(-3);
@show sign(3);
@show sign(0);
@show signbit(3);
@show signbit(-3);
@show copysign(3, -4);
@show flipsign(-3, -4);

abs(-3 + 4im) = 5.0
abs2(-3 + 4im) = 25
sign(-3) = -1
sign(3) = 1
sign(0) = 0
signbit(3) = false
signbit(-3) = true
copysign(3, -4) = -3
flipsign(-3, -4) = 3


## 5. Complex and Rational Numbers

In [23]:
# New to complex numbers only.
@show angle(2 + 2im) / pi * 180
@show sqrt(-1 + 0im)
@show isequal(1, 1 + 0im)
# Rational Numbers and thier unique operations
@show 4 // 8
@show 6 // 200
@show 5 // 8 * 3 // 12
@show 3 // 4 + 2 // 8
@show float(3 // 2)
@show isequal(3 // 2, 3/2);
# Floating point numbers have highest precedence.
# So, rantional numbers get typecasted to float
# when operated with a float. But rational numbers have
# a higher precedence than int so they remain rational
# when operated with an int.
@show 3 // 4 * (10)
@show 3 // 4 * (10.);

(angle(2 + 2im) / pi) * 180 = 45.0
sqrt(-1 + 0im) = 0.0 + 1.0im
isequal(1, 1 + 0im) = true
4 // 8 = 1//2
6 // 200 = 3//100
5 // 8 * 3 // 12 = 5//32
3 // 4 + 2 // 8 = 1//1
float(3 // 2) = 1.5
isequal(3 // 2, 3 / 2) = true
3 // 4 * 10 = 15//2
3 // 4 * 10.0 = 7.5


## 6. Strings!!

Some things to note:
 - Strings in Julia support all unicode characters with UTF-8 encoding.
 - All string types are subtypes of `AbstractString`. If you create a function expecting a string argument, you should declare the type as `AbstractString` in order to accept any string type.
 - Strings are immutable in Julia! Once assigned, they cannot be changed.
 - Char is implemented as an `AbstractChar` and is a 32 bit primitive type.

In [24]:
isvalid(Char, 0x1f0000)

false

In [25]:
# Interesting use of `end`
name = "Tirth Patel"
@show name[1]
@show name[end]
@show name[end-1]
# Slicing in Julia!
@show name[7:9]   # 8 inclusive!!!!
@show name[7:end]
# Notice that name[k] and nake[k:k] don't give the same results!
@show name[6:6] # string output
@show name[6] # char output
# SubString is another type of string which sub classes `AbstractString`
# and can be created using `SubString`.
@show SubString(name, 7, 9);

name[1] = 'T'
name[end] = 'l'
name[end - 1] = 'e'
name[7:9] = "Pat"
name[7:end] = "Patel"
name[6:6] = " "
name[6] = ' '
SubString(name, 7, 9) = "Pat"


In [26]:
typeof(name[6:9])

String

In [27]:
typeof(SubString(name, 6, 9))

SubString{String}

#### Note : `SubString` creates a VIEW while slicing creates a COPY!

In [28]:
# This shows that `SubString` creates a view while slicing creates a copy!!
str = "wow this is awesome" ^ 100
@btime str[6:900]
@btime SubString(str, 6, 900);

  81.347 ns (1 allocation: 1008 bytes)
  79.029 ns (1 allocation: 32 bytes)


### 6.1. Unicode and UTF-8

Whether these Unicode characters are displayed as escapes or shown as special characters depends on your terminal's locale settings and its support for Unicode. String literals are encoded using the UTF-8 encoding. UTF-8 is a variable-width encoding, meaning that not all characters are encoded in the same number of bytes ("code units"). In UTF-8, ASCII characters — i.e. those with code points less than 0x80 (128) – are encoded as they are in ASCII, using a single byte, while code points 0x80 and above are encoded using multiple bytes — up to four per character

String indices in Julia refer to code units (= bytes for UTF-8), the fixed-width building blocks that are used to encode arbitrary characters (code points). This means that not every index into a `String` is necessarily a valid index for a character. If you index into a string at such an invalid byte index, an error is thrown

In [29]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [30]:
# Error because In this case, the character ∀ is a three-byte character,
# so the indices 2 and 3 are invalid and the next character's index is 4.
s[2]

StringIndexError: StringIndexError("∀ x ∃ y", 2)

In [31]:
# this next valid index can be computed by nextind(s,1), and the next index after that by nextind(s,4) and so on.
@show nextind(s, 1);

nextind(s, 1) = 4


In [32]:
# Since end is always the last valid index into a collection,
# end-1 references an invalid byte index if the second-to-last
# character is multibyte
s[end-2]

StringIndexError: StringIndexError("∀ x ∃ y", 9)

In [33]:
# similarly you can use `prevind`
@show s[prevind(s, end, 1)];

s[prevind(s, end, 1)] = ' '


In [34]:
# We can also use `firstindex` and `lastindex` in a `for` loop
@show [i for i in s]
# We can also use `firstindex` and `lastindex` in a big `for` loop!!
for i in firstindex(s):lastindex(s)
    try
        print(s[i], " ");
    catch
        # ignore index error
    end
end

[i for i = s] = ['∀', ' ', 'x', ' ', '∃', ' ', 'y']
∀   x   ∃   y 

In [35]:
?eachindex # Returns a `iterable` or `collections` object

search: eachindex



```
eachindex(A...)
```

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a [`UnitRange`](@ref) if all inputs have fast linear indexing, a [`CartesianIndices`](@ref) otherwise). If the arrays have different sizes and/or dimensionalities, a DimensionMismatch exception will be thrown.

# Examples

```jldoctest
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
```


In [36]:
collect(eachindex(s))

7-element Array{Int64,1}:
  1
  4
  5
  6
  7
 10
 11

In [37]:
"Hello World" == "Hello World", "1 + 2 = 3" == "1 + 2 = $(1+2)"

(true, true)

### 6.2. String Methods!

In [38]:
# findfirst => Find firt occurence of something
findfirst(isequal('t'), "Tirth Patel")
# isequal(x) -> Create a function that compares its argument
#               to x using isequal, i.e. a function equivalent
#               to y -> isequal(y, x). The returned function
#               is of type Base.Fix2{typeof(isequal)}, which
#               can be used to implement specialized methods.

4

In [39]:
# finidlast
findlast(isequal('t'), "Tirth Patel")

9

In [40]:
# If not present, returns `nothing` object
typeof(findfirst(isequal('x'), "Tirth Patel"))

Nothing

In [41]:
# findnext and findprev helps to find the next occurence
# of a character and the previous occurence of a char.
@show findnext(isequal('t'), "Tirth Patel", 6)
@show findprev(isequal('t'), "Tirth Patel", 6);

findnext(isequal('t'), "Tirth Patel", 6) = 9
findprev(isequal('t'), "Tirth Patel", 6) = 4


In [42]:
# `occursin` function checks if a substing
# occurs in a string
@show occursin("Tirth", "Tirth Patel")
@show occursin('t', "Tirth Patel");

occursin("Tirth", "Tirth Patel") = true
occursin('t', "Tirth Patel") = true


In [43]:
# You can also use the `in` operator
# to check the occurence of an element
#  in a container.
@show 't' in "Tirth Patel"
@show "Tirth" in ["Tirth", "Patel"];

't' in "Tirth Patel" = true
"Tirth" in ["Tirth", "Patel"] = true


In [44]:
# Some other very obvious string methods
@show length("Tirth Patel")
@show length("\u2200 x \u2203 y")
@show length("\u2200 x \u2203 y", 3, 9) # the number of valid character indices in str from 3 to 9
@show thisind("\u2200 x \u2203 y", 3) # valid index to which 3 points which is 1.
@show nextind("\u2200 x \u2203 y", 2, 4)
@show prevind("\u2200 x \u2203 y", 9, 4);

length("Tirth Patel") = 11
length("∀ x ∃ y") = 7
length("∀ x ∃ y", 3, 9) = 4
thisind("∀ x ∃ y", 3) = 1
nextind("∀ x ∃ y", 2, 4) = 7
prevind("∀ x ∃ y", 9, 4) = 4


### 6.3. Regular Expressions in Julia

In [45]:
# TODO

## 7. Functions

In [46]:
# Normal Function
function f(x)
    return x .^ 2
end

# Inline function
f(x, y) = x .* y

# Lambda Function
lambda = x -> x .^ 2

#5 (generic function with 1 method)

In [47]:
f, lambda

(f, var"#5#6"())

In [48]:
x = randn(100, 1);

In [49]:
@btime f(x);

  75.848 ns (1 allocation: 896 bytes)


In [50]:
@btime f(x);

  76.819 ns (1 allocation: 896 bytes)


In [51]:
@btime lambda(x);

  75.876 ns (1 allocation: 896 bytes)


In [52]:
# if no `return` keyword is found, julia returns the
# last evaluated expression
function f(x,y,z)
    x .+ y .+ z
end

f([1 2], [3 4], [5 6])

1×2 Array{Int64,2}:
 9  12

In [53]:
# We can `return nothing` if we dont want the function
# to return anything.
function noreturn(x)
    println("x = $(x)");
    return nothing
end

typeof(noreturn([1. 2.]))

x = [1.0 2.0]


Nothing

In [54]:
# We can type the arguments to get very very highly
# efficient assembly code and super fast execution.
function typedf(x::Array{Float64}, y::Array{Float64}, z::Array{Float64})::Array{Float64}
    if all(y .< x) && all(z .< x)
        return x
    end
    if all(x .< y) && all(z .< y)
        return y
    end
    return z
end

typedf (generic function with 1 method)

In [55]:
@btime typedf(x, x, x);

  422.608 ns (4 allocations: 288 bytes)


In [56]:
# Tuples
@show (1, 2, 3)
@show (1, "Tirth Patel", 3//4);

(1, 2, 3) = (1, 2, 3)
(1, "Tirth Patel", 3 // 4) = (1, "Tirth Patel", 3//4)


In [57]:
# Named Tuples
nt = (name="Tirth", rollno="18BCE243", rank=1)

@show nt

println("Name : $(nt.name)")
println("Roll No : $(nt.rollno)")
println("Rank : $(nt.rank)")

nt = (name = "Tirth", rollno = "18BCE243", rank = 1)
Name : Tirth
Roll No : 18BCE243
Rank : 1


In [58]:
# Functions with multuiple return values
function multireturn(x, y)
    return x .+ y, x .* y
end

multireturn([1., 2.], [3., 4.])

([4.0, 6.0], [3.0, 8.0])

In [59]:
x, y = multireturn([1. 2.], 3.)
println(x)
println(y)

[4.0 5.0]
[3.0 6.0]


In [60]:
# Argument destucting : Using this we can name
# the arguments in a tuple when passed to a function
function adf((a,b),c)
    return a .* b .+ c
end

adf(([1. 2.], [3. 4.]), [5. 6.])

1×2 Array{Float64,2}:
 8.0  14.0

In [61]:
# Varargs
function varargf(a, b, c...)
    # + operator is also a function and
    # so is every operation. so we can pass
    # varargs directly to + function
    return +(a, b, c...)
end

varargf([1. 2.], [3. 4.], [5. 6.], [7. 8.], [9. 10.])

1×2 Array{Float64,2}:
 25.0  30.0

In [62]:
a = [1, 2, 3, 4]

+(a...) # Arrays can also be "unpacked" like python.

10

In [63]:
?...

search:



```
...
```

The "splat" operator, `...`, represents a sequence of arguments. `...` can be used in function definitions, to indicate that the function accepts an arbitrary number of arguments. `...` can also be used to apply a function to a sequence of arguments.

# Examples

```jldoctest
julia> add(xs...) = reduce(+, xs)
add (generic function with 1 method)

julia> add(1, 2, 3, 4, 5)
15

julia> add([1, 2, 3]...)
6

julia> add(7, 1:100..., 1000:1100...)
111107
```


In [64]:
# Optional Arguments

function adder(a, b=1., c=1.)
    return a .+ b .+ c
end

@show adder(10, 2, 3)
@show adder(10, 2)
@show adder(10);

adder(10, 2, 3) = 15
adder(10, 2) = 13.0
adder(10) = 12.0


In [65]:
# Keyword only arguments : Insert a `;` to make keyword only args
function keywordf(x1::Array{Float64,2}, x2::Array{Float64,2}; ls::Float64=1., amp::Float64=1.)::Array{Float64,2}
    res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1          )
    res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1          , size(x2)[1])
    res = res .- 2 .* (x1*x2')
    res = res ./ (2 .* ls.^2)
    return (amp.^2).*exp.(-res)
end

keywordf (generic function with 1 method)

In [66]:
x1 = randn(2000, 20)
x2 = randn(2000, 20);

In [67]:
@btime keywordf(x1, x2);

  117.919 ms (41054 allocations: 184.68 MiB)


In [68]:
# Do-Block syntax for function arguments
# We can vectorize the computation over multiple
# vectors using map and a `begin` `end` syntax.
map(args -> begin
                x1, x2, ls, amp = args
                res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1          )
                res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1          , size(x2)[1])
                res = res .- 2 .* (x1*x2')
                res = res ./ (2 .* ls.^2)
                return (amp.^2).*exp.(-res)
            end,
    [(x1, x2, 1., 1.), (x1, x2, 2., 3.)]
);

In [69]:
# Another way to write the same code is using `do` block:
map([(x1, x2, 1., 1.), (x1, x2, 2., 3.)]) do args
    x1, x2, ls, amp = args
    res =        reshape(mapslices(sum, x1.^2, dims=2), size(x1)[1], 1          )
    res = res .+ reshape(mapslices(sum, x2.^2, dims=2), 1          , size(x2)[1])
    res = res .- 2 .* (x1*x2')
    res = res ./ (2 .* ls.^2)
    return (amp.^2).*exp.(-res)
end;

### How does the `do` `end` block work??

Let's take the example below

```julia
func(...) do args
    # do something
end
```

It creates a lambda function with arguments `args` and the code between `do` `end` as function body. Then, it passes this lambda function to the function `func` as the first argument and the `...` as remaining arguments. After processing the `...` args, the function `func` calls the lambda function passing it these processed arguments. To make it clearer, let's take the example below

```julia
function func(f::Function, args...)
    # some preprocessing to get the arguments
    # for the lambda function
    fargs = preprocessor(args...)
    try
        res = f(fargs...)
    finally
        # do some post processing
        postprocessor(res...)
    end
end
```

In [70]:
# do blocks are like context manages in Python!!!
# An Example of opening and writing to a file is shown
open("context_managers_in_julia.md", "w") do f
    write(f, "## Do block in Julia\n\n")
    write(f, "This file was made using Julia's context managers!\n")
    write(f, "Isn't it awesome!\n")
end;

In [71]:
# Function composition

# Julia uses a lot of mathematical
# expressions which is good!
(sqrt ∘ +)(3.0, 6.0) # function composition => (f ∘ g)(x)  ≣  f(g(x))

3.0

In [72]:
# Composition of Function

# Julia is awesome, right?
@show 3.0 + 6.0 |> sqrt
@show ["This", "is", "a", "string"] .|> [uppercase, reverse, titlecase, length];

3.0 + 6.0 |> sqrt = 3.0
["This", "is", "a", "string"] .|> [uppercase, reverse, titlecase, length] = Any["THIS", "si", "A", 6]


## Control Flow

In [73]:
# Compound Expressions

# Method 1: Using `begin` `end`
@show z = begin
    x = 1
    y = 1
    x + y
end

# Method 2: Using `;` chains
@show z = (x = 1 ; y = 1 ; x + y);

z = begin
        #= In[73]:5 =#
        x = 1
        #= In[73]:6 =#
        y = 1
        #= In[73]:7 =#
        x + y
    end = 2
z = begin
        x = 1
        #= In[73]:11 =#
        y = 1
        #= In[73]:11 =#
        x + y
    end = 2


In [74]:
# C like ternary operator!!
a = 0
b = 1
(a > b) ? println("a > b") : println("a ≤ b") 

a ≤ b


In [75]:
# C like short circuit evaluations!!!
(a > b) || println("a ≤ b");

a ≤ b


In [76]:
# A use of these operators
function fact(n::Int)
    n ≥ 0 || error("n must be greater than or equal to 0 but found $n")
    n == 0 && return 1
    return n*fact(n-1)
end

fact (generic function with 1 method)

In [77]:
fact(-1)

ErrorException: n must be greater than or equal to 0 but found -1

### Exceptions and Exception Handling!

| Exception Name        | When is it thrown? |
| --------------        | ------------------ |
| ArgumentError         | argument not provided |
| BoundsError           | out of bounds access (like `a[0]`) |
| CompositeException    | - |
| DimensionMismatch     | dimensions are not matching for an operation to be performed. Be careful, most people forget to add a `.` before the function to indicate julia to broadcast an operation accross each element in the collection. Some collections like vectors don't support a square `^2` operation. You will have to do `.^2` for that behaviour.|
| DivideError           | illegal value during devide operation |
| DomainError           | value is out of the allowed domain |
| EOFError              | no eof found while parsing |
| ErrorException        | - |
| InexactError          | - |
| InitError             | - |
| InterruptException    | - |
| InvalidStateException | - |
| KeyError              | Key not present in struct or dict |
| LoadError             | - |
| OutOfMemoryError      | Memory full. Try to free some up |
| ReadOnlyMemoryError   | - |
| RemoteException       | - |
| MethodError           | The method you are trying to call doesn't exist. |
| OverflowError         | value more than the datatype can hold. Like passing `1e309` to a `Float64` |
| Meta.ParseError       | - |
| SystemError           | - |
| TypeError             | Type not supported |
| UndefRefError         | - |
| UndefVarError         | Variable not defined |
| StringIndexError      | String index is invalid |

In [78]:
# Play with exceptions here!
sqrt(-1.0)

DomainError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [79]:
# User defined exception!!
struct MyException <: Exception end

In [80]:
# We can throw that exception in some function
function throws_myexception(x::Int)::Int
    x ≥ 0 || throw(MyException())
    return x
end

throws_myexception (generic function with 1 method)

In [81]:
throws_myexception(-1)

MyException: MyException()

In [82]:
typeof(MyException()) <: Exception

true

In [83]:
# Try catch blocks in Julia! 

sqrt_second(x) = begin
    try
        sqrt(x[2])
    catch e
        if isa(e, DomainError)
            sqrt(complex(x[2], 0))
        elseif isa(e, BoundsError)
            sqrt(x)
        end
    end
end

sqrt_second (generic function with 1 method)

In [84]:
sqrt_second([2 -1])

0.0 + 1.0im

### Coroutins in Julia!!!!!!

This is the most amazing feature of julia and requires a notebook of its own.
Will try to do it this week but it may take some time as coroutines are very very
useful and difficult to understand!!

In [85]:
# TODO

## Scopes in Julia!

Julia uses something called lexical scoping!

This means that the variable undefined in the scope of the variable is inherited from the module in which function is defined.

Take the example below. `x` defined in module `Foo` is used in the function `f` and not the x defined in the main module afterwards!

In [88]:
module Foo
    x = 1
    f() = x
end;

In [89]:
import .Foo

x = -1

println(Foo.f())

1


In [90]:
# Let's play with modules
module A
    a = 1
end;

module B
    module C
        c = 2
    end;
    b = C.c

    import ..A
    d = A.a
end;

module D
    b = a
end;

UndefVarError: UndefVarError: a not defined

In [91]:
module E
    import ..A
    A.a = 3
end;

ErrorException: cannot assign variables in other modules

In [93]:
for i ∈ 1:10
    print(i)
end
println()
i

12345678910


UndefVarError: UndefVarError: i not defined

In [94]:
# nested scope can update the value in the parent scope
for i ∈ 1:1
    k = 0
    for j ∈ 1:1
        k = 2
    end
    print(k)
end

2

In [95]:
# it can be avoided by using a `local` keyword
for i ∈ 1:1
    k = 0
    for j ∈ 1:1
        local k = 2
    end
    print(k)
end

0

In [99]:
# You can also use `global` keyword inside a function
# if you have a variable with same name in the scope
# of the function but want to access the outer scope's
# variable
j = 1
for i ∈ 1:1
    for k ∈ 1:1
        global j += 1
    end
    println(j)
end

2


## Types in Julia!!!

Types are at the heart of Julia that provide it speed!
Static typing allows to reduce the computation time by several orders of magnitude.

Describing Julia in the lingo of type systems, it is: dynamic, nominative and parametric

Some important properties of types:
 - Only values, not variables, have types – variables are simply names bound to values
 - concrete types may not subtype each other: all concrete types are final and may only have abstract types as their supertypes
   This means that the function using concrete types can only be passed that type. no other type is a subtype of that type. On the other hand, the function using Abstract types can take as argument any subtype of that abstract type.


When appended to an expression computing a value, the `::` operator is read as "is an instance of". It can be used anywhere to assert that the value of the expression on the left is an instance of the type on the right. When the type on the right is concrete, the value on the left must have that type as its implementation – recall that all concrete types are final, so no implementation is a subtype of any other. When the type is abstract, it suffices for the value to be implemented by a concrete type that is a subtype of the abstract type. If the type assertion is not true, an exception is thrown, otherwise, the left-hand value is returned

In [103]:
x = 10
typeof(x)

Int64

In [105]:
function func(val)::Float64
    x::Float64 = val
    return val
end

func (generic function with 1 method)

In [108]:
# You can't do something like `x::Int = 10`
# because typing in global scope is not allowed
y = func(100)
typeof(y)

Float64

### Abstract types in Julia

Abstract types are declared using the `abstract type` keyword. The general syntaxes for declaring an abstract type are:

```julia
abstract type «name» end
abstract type «name» <: «supertype» end
```

The abstract type keyword introduces a new abstract type, whose name is given by `«name»`. This name can be optionally followed by `<:` and an already-existing type, indicating that the newly declared abstract type is a subtype of this "parent" type.

When no supertype is given, the default supertype is `Any` – a predefined abstract type that all objects are instances of and all types are subtypes of. In type theory, `Any` is commonly called "top" because it is at the apex of the type graph. Julia also has a predefined abstract "bottom" type, at the nadir of the type graph, which is written as `Union{}`. It is the exact opposite of `Any`: no object is an instance of `Union{}` and all types are supertypes of `Union{}`.

Let's consider some of the abstract types that make up Julia's numerical hierarchy

```julia
abstract type Number end
abstract type Real     <: Number end
abstract type AbstractFloat <: Real end
abstract type Integer  <: Real end
abstract type Signed   <: Integer end
abstract type Unsigned <: Integer end
```
The `Number` type is a direct child type of `Any`, and `Real` is its child. In turn, `Real` has two children (it has more, but only two are shown here; we'll get to the others later): `Integer` and `AbstractFloat`, separating the world into representations of integers and representations of real numbers. Representations of real numbers include, of course, floating-point types, but also include other types, such as rationals. Hence, `AbstractFloat` is a proper subtype of `Real`, including only floating-point representations of real numbers. `Integers` are further subdivided into `Signed` and `Unsigned` varieties.

The `<:` operator in general means "is a subtype of", and, used in declarations like this, declares the right-hand type to be an immediate supertype of the newly declared type. It can also be used in expressions as a subtype operator which returns true when its left operand is a subtype of its right operand

In [115]:
@show Int <: Number
@show Int <: AbstractFloat;

Int <: Number = true
Int <: AbstractFloat = false


### Primitive Types

A primitive type is a concrete type whose data consists of plain old bits. Classic examples of primitive types are float and integer types.

Unlike most languages, Julia lets you declare your own primitive types, rather than providing only a fixed set of built-in ones

The general syntaxes for declaring a primitive type are

```julia
primitive type «name» «bits» end
primitive type «name» <: «supertype» «bits» end
```