## 1. Integers and Floating Point Numbers

| Types Supported |
| --------------- |
| `Int8` |
| `UInt8` |
| `Int16` |
| `UInt16` |
| `Int32` |
| `UInt32` |
| `Int64` |
| `UInt64` |
| `Int128` |
| `UInt128` |
| `Bool` |
| `Float16` |
| `Float32` |
| `Float64` |

In [1]:
using BenchmarkTools

In [2]:
Sys.WORD_SIZE  # I have a Win64 system so the output will be => 64

64

In [3]:
display(0xdeadbeef)        # Hexadecimal numbers
display(0b01010)           # Binary number
display(bitstring(123))    # Returns the bit string of a integer number
display(bitstring(0.0))    # Returns the bitstring of a floating point number

0xdeadbeef

0x0a

"0000000000000000000000000000000000000000000000000000000001111011"

"0000000000000000000000000000000000000000000000000000000000000000"

In [4]:
1 % 0 # Throws a divide error

DivideError: DivideError: integer division error

In [5]:
rem(1, 0) # Throws a divide error

DivideError: DivideError: integer division error

In [6]:
display(eps(Float16)) # Displays the constant to get the
display(eps(Float32)) # next floating point number in the
display(eps(Float64)) # of the required bits

Float16(0.000977)

1.1920929f-7

2.220446049250313e-16

## Mathematical Operations and Elementary functions

| Rounding Functions |
| ------------------ |
| `round(x)` |
| `round(dtype, x)` |
| `floor(x)` |
| `floor(dtype, x)` |
| `ciel(x)` |
| `ciel(dtype, x)` |
| `trunc(x)` |
| `trunc(dtype, x)` |

| Division Functions |
| ------------------ |
|  |

In [7]:
0.0 == -0.0 # Value comparision

true

In [8]:
NaN == NaN # NaN is not equal to NaN

false

In [9]:
[1 NaN] == [1 NaN] # So, this also returns false

false

In [10]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 > 0 # Expressions can be chained

true

In [11]:
0 .< [0 1 2 3 4 5 4 3 2 1] .< 2 # Element-wise value comparision

1×10 BitArray{2}:
 0  1  0  0  0  0  0  0  0  1

In [12]:
# Julia provides additional functions to test numbers for special values,
# which can be useful in situations like hash key comparisons
display(isequal(0.0, -0.0))                       # Hash Key comparision
display(isfinite(10000000000000000000000000.0))   # Is it finite?
display(isinf(Inf32))                             # Is it infinite?
display(isinf(NaN))                               # Is it infinite?
display(isnan(NaN64))

false

true

true

false

true

In [13]:
f(x) = x^2
x = randn(5, 5)
display(f.(x))
display(f(x))

5×5 Array{Float64,2}:
 0.371728  4.62      1.8053     1.1207     0.975388
 0.159682  2.80412   0.0176253  1.14287    2.64511
 2.17447   3.00108   0.151701   0.285039   0.00846763
 0.259641  0.687098  0.572721   0.0588428  5.77203
 1.09779   0.113024  0.132189   1.07238    2.15599

5×5 Array{Float64,2}:
  3.06833    1.24835    2.06995    1.0902     5.31477
  1.7806     1.83582   -2.10787   -2.72116   -8.06235
  0.605521   0.531746   1.9255     0.533077   2.89188
 -3.73624   -2.02697   -0.399521   1.79602    1.02387
 -1.04245    1.424      2.62835    0.325448   6.19203

In [14]:
using Base

In [15]:
println(Base.operator_precedence(:+), " ", Base.operator_precedence(:*), " ", Base.operator_precedence(:.))
println(Base.operator_precedence(:sin), " ", Base.operator_precedence(:+=), " ", Base.operator_precedence(:(=)))

11 12 17
0 1 1


In [16]:
-4 % 5 # true division unlike python which is good :-)

-4

## Convertions

Julia supports three forms of numerical conversion, which differ in their handling of inexact conversions.

The notation T(x) or convert(T,x) converts x to a value of type T.

 - If T is a floating-point type, the result is the nearest representable value, which could be positive or negative infinity.
 - If T is an integer type, an InexactError is raised if x is not representable by T.
 - x % T converts an integer x to a value of integer type T congruent to x modulo 2^n, where n is the number of bits in T. In other words, the binary representation is truncated to fit.

The Rounding functions take a type T as an optional argument. For example, round(Int,x) is a shorthand for Int(round(x)).

In [17]:
import Base:convert

In [18]:
@show 127 % Int8
@show 128 % Int8
@show round(Int8,127.4)
round(Int8,127.6)

127 % Int8 = 127
128 % Int8 = -128
round(Int8, 127.4) = 127


InexactError: InexactError: trunc(Int8, 128.0)

In [19]:
@which convert(Complex{Int32}, 1+2im)

convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7

In [20]:
# You can overload convert method with user defined datatypes
convert(::Type{Int8}, x::String) = [Number(i) for i in x]

convert (generic function with 184 methods)

In [21]:
convert(Int8, "tirth")

5-element Array{UInt32,1}:
 0x00000074
 0x00000069
 0x00000072
 0x00000074
 0x00000068

## Signed and absolute valued functions

| Function | Description |
| -------- | ----------- |
| `abs(x)` | Abs. |
| `abs2(x)` | Absolute value squared! Can be useful for finding euclidean distance. |
| `sign(x)` | Sign. |
| `signbit(x)` | Indicating weather the signbit is on or off. |
| `copysign(x, y)` | A value with magnitude of x and sign of y. |
| `flipsign(x, y)` | A value with magnitude of x and sign of x\*y |

In [22]:
@show abs(-3 + 4im);
@show abs2(-3 + 4im);
@show sign(-3);
@show sign(3);
@show sign(0);
@show signbit(3);
@show signbit(-3);
@show copysign(3, -4);
@show flipsign(-3, -4);

abs(-3 + 4im) = 5.0
abs2(-3 + 4im) = 25
sign(-3) = -1
sign(3) = 1
sign(0) = 0
signbit(3) = false
signbit(-3) = true
copysign(3, -4) = -3
flipsign(-3, -4) = 3


## Complex and Rational Numbers

In [23]:
# New to complex numbers only.
@show angle(2 + 2im) / pi * 180
@show sqrt(-1 + 0im)
@show isequal(1, 1 + 0im)
# Rational Numbers and thier unique operations
@show 4 // 8
@show 6 // 200
@show 5 // 8 * 3 // 12
@show 3 // 4 + 2 // 8
@show float(3 // 2)
@show isequal(3 // 2, 3/2);
# Floating point numbers have highest precedence.
# So, rantional numbers get typecasted to float
# when operated with a float. But rational numbers have
# a higher precedence than int so they remain rational
# when operated with an int.
@show 3 // 4 * (10)
@show 3 // 4 * (10.);

(angle(2 + 2im) / pi) * 180 = 45.0
sqrt(-1 + 0im) = 0.0 + 1.0im
isequal(1, 1 + 0im) = true
4 // 8 = 1//2
6 // 200 = 3//100
5 // 8 * 3 // 12 = 5//32
3 // 4 + 2 // 8 = 1//1
float(3 // 2) = 1.5
isequal(3 // 2, 3 / 2) = true
3 // 4 * 10 = 15//2
3 // 4 * 10.0 = 7.5


## Strings!!

Some things to note:
 - Strings in Julia support all unicode characters with UTF-8 encoding.
 - All string types are subtypes of `AbstractString`. If you create a function expecting a string argument, you should declare the type as `AbstractString` in order to accept any string type.
 - Strings are immutable in Julia! Once assigned, they cannot be changed.
 - Char is implemented as an `AbstractChar` and is a 32 bit primitive type.

In [24]:
isvalid(Char, 0x1f0000)

false

In [25]:
# Interesting use of `end`
name = "Tirth Patel"
@show name[1]
@show name[end]
@show name[end-1]
# Slicing in Julia!
@show name[7:9]   # 8 inclusive!!!!
@show name[7:end]
# Notice that name[k] and nake[k:k] don't give the same results!
@show name[6:6] # string output
@show name[6] # char output
# SubString is another type of string which sub classes `AbstractString`
# and can be created using `SubString`.
@show SubString(name, 7, 9);

name[1] = 'T'
name[end] = 'l'
name[end - 1] = 'e'
name[7:9] = "Pat"
name[7:end] = "Patel"
name[6:6] = " "
name[6] = ' '
SubString(name, 7, 9) = "Pat"


In [26]:
typeof(name[6:9])

String

In [27]:
typeof(SubString(name, 6, 9))

SubString{String}

#### Note : `SubString` creates a VIEW while slicing creates a COPY!

In [28]:
# This shows that `SubString` creates a view while slicing creates a copy!!
str = "wow this is awesome" ^ 100
@btime str[6:900]
@btime SubString(str, 6, 900);

  88.657 ns (1 allocation: 1008 bytes)
  92.364 ns (1 allocation: 32 bytes)


### Unicode and UTF-8

Whether these Unicode characters are displayed as escapes or shown as special characters depends on your terminal's locale settings and its support for Unicode. String literals are encoded using the UTF-8 encoding. UTF-8 is a variable-width encoding, meaning that not all characters are encoded in the same number of bytes ("code units"). In UTF-8, ASCII characters — i.e. those with code points less than 0x80 (128) – are encoded as they are in ASCII, using a single byte, while code points 0x80 and above are encoded using multiple bytes — up to four per character

String indices in Julia refer to code units (= bytes for UTF-8), the fixed-width building blocks that are used to encode arbitrary characters (code points). This means that not every index into a `String` is necessarily a valid index for a character. If you index into a string at such an invalid byte index, an error is thrown

In [29]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [30]:
# Error because In this case, the character ∀ is a three-byte character,
# so the indices 2 and 3 are invalid and the next character's index is 4.
s[2]

StringIndexError: StringIndexError("∀ x ∃ y", 2)

In [31]:
# this next valid index can be computed by nextind(s,1), and the next index after that by nextind(s,4) and so on.
@show nextind(s, 1);

nextind(s, 1) = 4


In [32]:
# Since end is always the last valid index into a collection,
# end-1 references an invalid byte index if the second-to-last
# character is multibyte
s[end-2]

StringIndexError: StringIndexError("∀ x ∃ y", 9)

In [33]:
# similarly you can use `prevind`
@show s[prevind(s, end, 1)];

s[prevind(s, end, 1)] = ' '


In [34]:
# We can also use `firstindex` and `lastindex` in a `for` loop
@show [i for i in s]
# We can also use `firstindex` and `lastindex` in a big `for` loop!!
for i in firstindex(s):lastindex(s)
    try
        print(s[i], " ");
    catch
        # ignore index error
    end
end

[i for i = s] = ['∀', ' ', 'x', ' ', '∃', ' ', 'y']
∀   x   ∃   y 

In [35]:
?eachindex # Returns a `iterable` or `collections` object

search: eachindex



```
eachindex(A...)
```

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a [`UnitRange`](@ref) if all inputs have fast linear indexing, a [`CartesianIndices`](@ref) otherwise). If the arrays have different sizes and/or dimensionalities, a DimensionMismatch exception will be thrown.

# Examples

```jldoctest
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
```


In [36]:
collect(eachindex(s))

7-element Array{Int64,1}:
  1
  4
  5
  6
  7
 10
 11